/* PART B – Aggregate Functions (Questions 41–60)

41.Display the total number of registered customers. */
select count(*) as No_of_customers
from customers;

/* 42.Display the total number of restaurants. */
select count(*) as No_of_restaurants
from restaurants;

/* 43.Display the total number of customer orders. */
select count(*) as No_of_orders
from orders; 

/* 44.Display the total number of completed payments. */
select count(*) as successfull_payment
from payments
where PaymentStatus = 'Success'; 

/* 45.Display the total revenue generated through completed payments. */
select sum(Amount) as Total_Revenue
from payments
where PaymentStatus = 'success';

/* 46.Display the average order amount. */
select avg(TotalAmount) as Average_amount
from orders;

/* 47.Display the highest order amount. */
select max(TotalAmount) as High_Amount
from orders;

/* 48.Display the lowest order amount. */
select min(TotalAmount) as LOW_Amount
from orders;

/* 49.Display the average customer review rating. */
select avg(FoodRating) as Average_Rating
from reviews;

/* 50.Display the average review rating rounded to two decimal places. */
select round(avg(FoodRating), 2) as Average_Rating
from reviews;

/* 51.Display the number of customers in each city. */
select City, count(*) as No_of_customers
from customers
group by City;

/* 52.Display the number of restaurants in each city. */
select City, count(*) as No_of_Restaurants
from restaurants
group by City;

/* 53.Display the total revenue generated by each payment method. */
select PaymentMethod, sum(Amount) as Total_revenue
from payments
group by PaymentMethod;

/* 54.Display the number of transactions for each payment method. */
select PaymentMethod, count(*) as No_of_transactions
from payments
group by PaymentMethod;

/* 55.Display the number of reviews for each rating. */
select FoodRating, count(*)
from reviews
group by FoodRating;

/* 56.Display the number of menu items in each food category. */
select CategoryName, count(ItemName) as No_of_Foods
from menucategories c
inner join menuitems m on c.CategoryID = m.CategoryID
group by CategoryName;

/* 57.Display cities having more than five registered customers. */
select City, count(*) as No_of_customers
from customers
group by City
having No_of_customers > 5;

/* 58.Display payment methods generating revenue greater than ₹20,000. */ 
select PaymentMethod, sum(Amount) as 'Revenue'
from payments
group by PaymentMethod
having Revenue > 20000;

/* 59.Display the average menu price for each food category. */ 
select CategoryID, round(avg(Price),2)
from menuitems
group by CategoryID; 

/* 60.Display payment-method-wise transaction count, total revenue, average payment, highest payment, and lowest payment. */
select PaymentMethod, 
		count(*) as No_of_transactions,
		sum(Amount) as Total_Revenue,
        round(avg(Amount),2) as Average_Amount,
        max(Amount) as Highest_Amount,
        min(Amount) as Lowest_Amount
from payments
where PaymentStatus = 'success'
group by PaymentMethod;